### ISSUE TITLE
Uncaught TypeError when clicking nav

### ISSUE THREAD

**Issue by marpaia** [keegn/gatsby-starter-saas-marketing#14]
There is currently an uncaught TypeError when one clicks any nav item. I've reproduced this locally and it also is an issue on the currently deployed site: https://gatsby-starter-saas-marketing.netlify.app/

<img width="1259" alt="Screen Shot 2020-05-11 at 1 26 22 PM" src="https://user-images.githubusercontent.com/927168/81603137-10370580-938b-11ea-963c-b7804b578b68.png">

**Comment by marpaia** [comment]
Ah, I see now that this is just because those sections don't exist.

**Comment by keegn** [comment]
Thanks for mentioning @marpaia. I will add some navigation info to the readme.
