### ISSUE TITLE
Firefox Developer Edition renders page as if it were mobile

### ISSUE THREAD

**Issue by todofixthis** [keegn/gatsby-starter-saas-marketing#15]
I'll start this off by saying I don't think this is actually gatsby-starter-saas-marketing's fault, but I am not familiar enough with gatsby to know where to look.  It would be super helpful if you could point me in the right direction 😺

Repro:
1. `gatsby new gatsby-starter-saas-marketing https://github.com/keegn/gatsby-starter-saas-marketing`
2. `cd gatsby-starter-saas-marketing`
3. `gatsby develop`
4. Open `http://localhost:8000` in [Firefox Developer Edition](https://www.mozilla.org/en-US/firefox/developer/).
    * Note that the page renders correctly when loaded in Firefox; it only seems to render incorrectly in Firefox Developer Edition.

<details>
<summary>Expected Result:</summary>

![Desktop version](https://www.gatsbyjs.org/static/14db7fb6f746b2797de54ed6515b978d/54967/8e0484ac0efc89a074a106c008db52d5.png)

</details>

<details>
<summary>Actual Result:</summary>

![Mobile version](https://user-images.githubusercontent.com/202040/82616886-9f150f00-9c22-11ea-8160-6aa9bb2ff419.png)

</details>

**Comment by keegn** [comment]
Oh that's interesting. Thanks for mentioning. I'll check it out 👍

**Comment by keegn** [comment]
@todofixthis I'm running Firefox Developer Edition `77.0beta` and it seems to be rendering like it should. This screenshot was taken at `1280px` window width. 
<img width="1275" alt="Screen Shot 2020-05-22 at 5 23 53 PM" src="https://user-images.githubusercontent.com/7526703/82713646-47da6300-9c51-11ea-865f-aeefe7ba381e.png">

**Comment by todofixthis** [comment]
Hmmm.  Very interesting; thanks for looking into this!  I'll do some more digging; maybe it's related to an extension or similar.  Will report back with my findings.

**Comment by todofixthis** [comment]
Weird; I cleared my cache and reloaded, and now it is rendering correctly 🤷🏻‍♂️

Maybe not the most satisfying ending, but a happy one nonetheless 😅  Thanks again for looking into this; it was super helpful to eliminate some variables!
