### ISSUE TITLE
node_modules/sharp makes problems

### ISSUE THREAD

**Issue by newt0** [keegn/gatsby-starter-saas-marketing#17]
Thanks for the great starter!

Two weeks ago it was working fine.
But today I newly installed your starter, I was unable to run it on local server.
Perhaps it's not your starter's fault, maybe it's the `sharp module`.

The command I executed:

```
gatsby new gatsby-starter-sas-marketing https ://github.com/keegn/gatsby-starter-saas- marketing

cd gatsby-starter-saas-marketing

gatsby develop
```

Description of the error output:

```
Something went wrong installing the "sharp" module

Cannot find module '../build/Release/sharp.node'
Require stack:
- /Users/kyo/dev/Gastby/gatsby-starter-saas-marketing/node_modules/sharp/lib/constructor.js
- /Users/kyo/dev/Gastby/gatsby-starter-saas-marketing/node_modules/sharp/lib/index.js
- /Users/kyo/dev/Gastby/gatsby-starter-saas-marketing/node_modules/gatsby-plugin-sharp/safe-sharp.js
- /Users/kyo/dev/Gastby/gatsby-starter-saas-marketing/node_modules/gatsby-plugin-sharp/index.js
- /Users/kyo/dev/Gastby/gatsby-starter-saas-marketing/node_modules/gatsby-transformer-sharp/extend-node-type.js
- /Users/kyo/dev/Gastby/gatsby-starter-saas-marketing/node_modules/gatsby-transformer-sharp/gatsby-node.js
- /Users/kyo/dev/Gastby/gatsby-starter-saas-marketing/node_modules/gatsby/dist/bootstrap/resolve-module-exports.js
- /Users/kyo/dev/Gastby/gatsby-starter-saas-marketing/node_modules/gatsby/dist/bootstrap/load-plugins/validate.js
- /Users/kyo/dev/Gastby/gatsby-starter-saas-marketing/node_modules/gatsby/dist/bootstrap/load-plugins/load.js
- /Users/kyo/dev/Gastby/gatsby-starter-saas-marketing/node_modules/gatsby/dist/bootstrap/load-plugins/index.js
- /Users/kyo/dev/Gastby/gatsby-starter-saas-marketing/node_modules/gatsby/dist/bootstrap/index.js
- /Users/kyo/dev/Gastby/gatsby-starter-saas-marketing/node_modules/gatsby/dist/commands/develop.js
- /Users/kyo/.nodebrew/node/v14.2.0/lib/node_modules/gatsby-cli/lib/create-cli.js
- /Users/kyo/.nodebrew/node/v14.2.0/lib/node_modules/gatsby-cli/lib/index.js
- /Users/kyo/.nodebrew/node/v14.2.0/lib/node_modules/gatsby-cli/cli.js

- Remove the "node_modules/sharp" directory, run "npm install" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/en/stable/install/
- Search for this error at https://github.com/lovell/sharp/issues
```

**Comment by newt0** [comment]
As the error message said, after finding and removing `node_modules/sharp` from the finder, I ran the `npm install`.
But I still can't run gatsby develop.

Description of the error output:
```
UNHANDLED REJECTION Unable to find plugin "gatsby-transformer-sharp". Perhaps you need to install its package?
  Error: Unable to find plugin "gatsby-transformer-sharp". Perhaps you need to install its package?  
```

As the error message said,  ran the `npm install gatsby-transformer-sharp`.
But I still can't run `gatsby develop`.

Description of the error output:
```
Error: Unable to find plugin "gatsby-plugin-sharp". Perhaps you need to install its package?
```

**Comment by newt0** [comment]
https://github.com/gatsbyjs/gatsby/issues/4693#issuecomment-427256961

I've solved it!

Here are the steps:

1. Delete `node_modules` folder
2. Clear npm cache `npm cache clean --force`
3. Re-install packages by running `npm install'
4. Try again to run `gatsby develop` on your terminal/cmd. 

#https://github.com/gatsbyjs/gatsby/issues/4693#issuecomment-427256961

**Comment by keegn** [comment]
Thanks @newt0. I'll try to reproduce this and will update accordingly.

**Comment by keegn** [comment]
Just ran the following:

`gatsby new gatsby-starter-sas-marketing https ://github.com/keegn/gatsby-starter-saas- marketing`

`cd gatsby-starter-saas-marketing`

`yarn`

Did not produce any errors and compiled successfully. Let me know if the issue persists for you - until then I'll close this. Thanks again.

**Comment by ohyunkyo** [comment]
> [gatsbyjs/gatsby#4693 (comment)](https://github.com/gatsbyjs/gatsby/issues/4693#issuecomment-427256961)
> 
> I've solved it!
> 
> Here are the steps:
> 
> 1. Delete `node_modules` folder
> 2. Clear npm cache `npm cache clean --force`
> 3. Re-install packages by running `npm install'
> 4. Try again to run `gatsby develop` on your terminal/cmd.
> 
> #[gatsbyjs/gatsby#4693 (comment)](https://github.com/gatsbyjs/gatsby/issues/4693#issuecomment-427256961)

its work for me!!
