### ISSUE TITLE
Does Not Build on M1 Mac - Sharp Plugin

### ISSUE THREAD

**Issue by gerdums** [keegn/gatsby-starter-saas-marketing#83]
## Description

This does not build on M1 Macs

### Steps to reproduce

Run `yarn` or `npm install` on an M1 Mac and it will fail

### Expected result

The dependencies should be installed to allow you to run the site locally

### Actual result

Error code 1

### Environment

| Tool    | Version |
| ------- | ------- |
| Chrome |    103     |
| MacOS    |     12    |
| node    |     16.15.0    |
| npm     |    8.5.5     |

**Comment by keegn** [comment]
@gerdums Thanks. I'll look into this when I get a chance. Do you mind if I tag you on a PR so that you can test a fix branch locally when it is ready? (I don't have an M1 yet)
